### ISSUE TITLE
"Command cannot be executed in this world"

### ISSUE THREAD

**Issue by ghost** [Qballl/WildAddon#1]
When a player issues the /wild command, they are told the "Command cannot be executed in this world". As far as I know, I have set up the config correctly - the world it can be used in ; the world to be teleported to. Here is the error it spills out in the console:
[20:55:06] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to WildAddon v1.9.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1345) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at me.Qball.Wild.Utils.GetRandomLocation.getRandomLoc(GetRandomLocation.java:81) ~[?:?]
	at me.qball.wildaddon.WildAddon.getWorld(WildAddon.java:166) ~[?:?]
	at me.qball.wildaddon.WildAddon.checkPerms(WildAddon.java:105) ~[?:?]
	at me.qball.wildaddon.WildAddon.onWildCommand(WildAddon.java:92) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-54ec0b8-1ac133e]
	... 16 more

**Comment by Qballl** [comment]
Send both the wild config and addon config please using a pastebin like site ie pastebin,hatebin and I'll look at the line that throwi ng the error

**Comment by Qballl** [comment]
Im closing this due to inactivity
